export const APP_ROUTES = {
  LANDING: {
    ROOT: 'landing',
    HOME: 'home',
    PRODUCTS: 'products',
    PRODUCT_DETAILS: 'products',
    CATEGORIES: 'categories',
    OCCASIONS: 'occasions',
    CONTACT: 'contact',
    ABOUT: 'about',
    WISHLIST: 'Wishlist',
    CART: 'cart',
    CHECKOUT: 'checkout',
  },
  AUTH: {
    ROOT: 'auth',
    LOGIN: 'login',
    REGISTER: 'register',
    FORGET_PASSWORD: 'forget-password',
    SET_PASSWORD: 'set-password',
    RESET_PASSWORD: 'reset-password',
    PROFILE: 'profile',
  },
  DASHBOARD: {
    ROOT: 'dashboard',
    OVERVIEW: 'overview',
    PRODUCTS: 'products',
    ADD_PRODUCT: 'products/form',
    EDIT_PRODUCT: 'products/form/:id',
    ACCOUNT: 'account',
    CHANGE_PASSWORD: 'changePassword',
    CATEGORIES: 'categories',
    ADD_CATEGORY: 'categories/add',
    UPDATE_CATEGORY: 'categories/update/:id',
  },
};
